### ISSUE TITLE
Organizacja pracy

### ISSUE THREAD

**Issue by konik32** [maniekstasz/OfferSeeker#1]
1. Opieramy się głównie na githubie z dwóch powodów:
   <ul><li>Wszyscy go w miarę znamy.</li>
   <li>Lepiej wszystko mieć w jednym miejscu (kod, ogłoszenia, dyskusje, problemy)</li></ul>
2. Będę starał się tworzyć milestony poszczególnych etapów z planowanym terminem ich zakończenia.
3. Jak już wspominałem wszystkie dyskusje, pytania, problemy wrzucamy tutaj w formie issues lub komentarzy. Używajcie odpowiednich etykiet oraz przyporządkowujcie issues do odpowiedniego milestona.
4. Dodawajcie etykiety jeśli uważacie, że jakiejś brakuje.
5. <b>Sprawdzajcie githuba co najmniej raz dziennie</b>
6. Repozytorium jest prywatne.
7. Czekam na wszelkie pomysły również te dotyczące zarządzania.
8. Jak coś jeszcze wymyślę to dopisze

**Comment by gkostalkowicz** [comment]
Temat pracy. Nie widzę go w innym miejscu na gh, więc pozwolę sobie wrzucić tutaj.

**Temat 9
Poszukiwacz ofert**

**Cel:**
Aplikacja śledząca ogłoszenia na serwisach i raportująca ogłoszenia zgodne z oczekiwaniami użytkownika

**Opis:**
Aplikacja powinna korzystać z dowolnych wskazanych serwisów – ebay, grono, gumtree itp. Nie powinno być w aplikacji sztywnych interfejsów do konkretnych serwisów, aplikacja powinna sama wydzielić ogłoszenia ze strony poprzez analizę powtarzających się wzorców kodu. Aplikacja powinna też przeszukiwać podlinkowane strony, sprawdzając czy znajdują się na nich ogłoszenia – i jeśli tak to też je analizować. Wyszukiwanie ogłoszeń ma się odbywać cyklicznie (np. co godzinę/dzień itp). Aplikacja powinna raportować znalezione ogłoszenia odpowiadające poszukiwaniu użytkownika – a także na podstawie feedbacku od użytkownika uczyć się oceniać te ogłoszenia (i poprawiać swoją skuteczność).

**Technologia:**
(Java, C/C++, Perl), architektura klient/serwer

**Komponenty do przygotowania:**
Metoda oceny struktury nieznanej strony i wydzielania ogłoszeń.
Serwer zbierający informacje z sieci
Aplikacja kliencka pozwalająca na wygodne przeglądanie nowych i starych wątków, generowanie statystyk itp.

**Docelowe platformy uruchomieniowe / pakiety instalacyjne:**
Serwer: Aplikacja możliwa do skompilowania (make) i uruchomienia w środowisku linux + paczka dla dystrybucji Debian
Klient: Aplikacja możliwa do skompilowania (make) i uruchomienia w środowisku linux (KDE/QT) + paczka dla dystrybucji Debian, oraz aplikacja z instalatorem dla systemu windows (XP, 7). Instalator nie powinien wymagać pre-instalowania innego oprogramowania poza dostępnym standardowo w systemie windows.
Uwaga: Wykorzystanie jako klienta przeglądarki internetowej będzie uznane za niepełne wykonanie zadania

**Comment by konik32** [comment]
Nie piszcie w zamkniętych issues. #2 dotyczył pierwszego spojrzenia na projekt. Jeśli macie pomysł dotyczący konkretnego modułu piszcie w issue tego modulu.

**Comment by ghost** [comment]
Mam prośbę odnośnie stylu programowania. Skoro w wymaganiach mamy punkt _Testy automatyczne (jednostkowe i funkcjonalne) aplikacji_ to może od razu piszmy chociaż te testy jednostkowe, żeby tego nie robić na końcu, bo to totalnie mija się z celem.

**Testy jednostkowe**
Na przykładzie dodawania:

`int Sum (int opA, int opB) {
 return opA + opB;
}`

Wiemy, że 2 + 5 daje 7:

```
void testSum() {
 int opA = 2; int opB = 5;
 int result = Sum(opA, opB);
 if (result != 7) -> zgłoś błąd
}
```

**Testy funkcjonalne**
W skrócie - czy system pracuje zgodnie ze specyfikacją?

**Test-driven development**
To nie jest w gruncie rzeczy sprawa łatwa, a czasem nawet nie możliwa do zrealizowania, więc ten punkt to bardziej propozycja. Styl wymusza używanie testów. Kolejne kroki dla Test-driven:
- najpierw test sprawdzający dodawaną funkcjonalność (test nieudany)
- implementacja funkcjonalności (test udany)
- refaktoryzacja napisanego kodu, żeby spełniał on oczekiwane standardy.

EDIT
No nie mówiąc już o **komentarzach** ale pisanych z głową.

**Comment by bambalooon** [comment]
Jeśli chodzi o moją część algorytmu, to będę starał się pisać cały czas w TDD, bo w pracy to cały czas stosuje.
Więc jestem jak najbardziej za.

**Comment by gkostalkowicz** [comment]
**Wymagania projektu:**
http://forum.stosowana.pl/download/file.php?id=1171

**Comment by ghost** [comment]
Mam propozycje utworzenia milestone z dość krótkim deadline do utworzenia interfejsów swoich modułów

**Comment by konik32** [comment]
@up będzie zrobione dzisiaj wieczorem

**Comment by bambalooon** [comment]
Proponuje jako serwer wykorzystać jboss'a.
ORM: Hibernate
I do bazy postgress'a - mamy to dość świeże.

**Comment by konik32** [comment]
Serwer: jetty -postawione
ORM: hibernate -postawione
Baza: na razie mysql, jutro może być postgresql, ale proponuje hsqldb file database (powód w #13)
Dzisiaj wypróbowałem bardzo pomocną biblioteke http://projectlombok.org/ i stwierdzam, że można byłoby ją użyć.

**Comment by konik32** [comment]
Prosiłbym o nie zmienianie konfiguracji pomów. Oczywiście można dodawać dependecies i pluginy, ale proszę nie zmieniać tego co już jest. Jeśli chcecie zmienić coś w czyimś module zróbcie brancha.

**Comment by konik32** [comment]
Starajcie się nie używać xml, a już na pewno nie do konfiguracji http://examples.javacodegeeks.com/enterprise-java/spring/beans-spring/spring-3-java-config-example/

**Comment by bambalooon** [comment]
Musimy się też dowiedzieć, czy możemy użyć jakiegoś cudzego rozwiązania w naszym projekcie, sprawdzić jego i naszą licencję...

**Comment by ghost** [comment]
btw. umie ktoś zmienić autora commitów na gicie z Bartłomiej Hebda na bartQH? :P

**Comment by bambalooon** [comment]
git config --global user.name "Jan Nowak"

**Comment by ghost** [comment]
sorry musiałem dodać poma z parserem html bo już mnie szlag jasny trafiał przy tej dżawie.

**Comment by bambalooon** [comment]
Jaki jest ostateczny termin oddania projektu?
Zrobiłby ktoś milestone, żeby nikt nie miał w przyszłości wątpliwości?
