### ISSUE TITLE
Raport 1 - Stworzenie wykresu sieciowego

### ISSUE THREAD

**Issue by rampler** [maniekstasz/OfferSeeker#10]
Cześć,
dziś postanowiłem trochę się pobawić z tym wykresem i powstało mi coś takiego:
![diagramsieciowy](https://cloud.githubusercontent.com/assets/3811596/4692933/394212ea-5781-11e4-907f-ecb4ec3c9848.png)

Nie wiem czy jest to dobrze, dlatego prosiłbym @bambalooon i @worldofpiesels  o sprawdzenie i ewentualne poprawienie czegoś co Wam się nie podoba. Plik MS Visio możecie pobrać stąd:
https://drive.google.com/file/d/0B3fCB22qU-KcN05fSEhpNE5RS28/view?usp=sharing

**Comment by bambalooon** [comment]
Rozumiem, że to powinien być harmonogram przed wykonaniem zadania...
Ale mimo wszystko powinien on chyba częściej zakładać delay, w zasadzie idealnie jest chyba zrobić na podstawie tego co było w realu.
@konik32 pilnowałeś czasu - mógłbyś podać szacunkowe czasy tych akcji?
Pamiętam, że wg. harmonogramu mieliśmy na początku robić 5min pierwsze 2! wsporniki, każda grupa - może warto by to też podzielić na 3 równoległe zadania. I dodać osobne zadanie nadzoru - choć nie jestem pewien czy tu ma rację bytu.
Potem mieliśmy opóźnienie - nie wiem ile dokładnie - 2/3min może. I tutaj dalej moim zdaniem powinny być 3 równoległe zadania. 2 - budowa pierwszego prototypu, i kolejne 2: wydłużanie i budowa kolejnego. I równolegle: budowa kolejnych wsporników.
Zgadzacie się z tym co mówię? Chciałem dojść do porozumienia, zanim coś zmienię w wykresie.

**Comment by konik32** [comment]
Czasy: 0-6 min cztery grupy robiły moduły, 6-12 dwie grupy robiły nogi, pozostałe dwie dalej moduły, 12-15 przyklejanie podstaw i rozpórek.

**Comment by bambalooon** [comment]
Ok, dzięki - o to właśnie mi chodziło.
Czyli w pierwszym mamy 1min opóźnienia wzg. planu, można w harmonogramie dać bezpiecznie nawet 2min.

**Comment by rampler** [comment]
Tylko trzeba pamiętać, że ścieżka krytyczna musi mieć chyba zawsze opóźnienie 0 jeżeli się nie mylę. Przynajmniej w każdym przypadku jaki widziałem tak było.

**Comment by rampler** [comment]
Wykresy poszły na mail.
