### ISSUE TITLE
Podstawowa wersja PageProcessora

### ISSUE THREAD

**Issue by konik32** [maniekstasz/OfferSeeker#15]
1. Trzy Interfejsy do komunikacji z serwerem:
   - wywoływanie algorytmu
   - obsługa feedbacku od użytkownika
   - zwracanie danych
2. Wersja powinna umożliwiać ocenę czy coś jest ogłoszeniem czy nie (mniej lub bardziej trafnie) i zwracać je przynajmniej jako html.

**Comment by bambalooon** [comment]
Moim zdaniem dane nie powinny być zwracane jako HTML - nie o to chodzi w naszym module.
Powinniśmy tak jak napisał @bartQH w #6 zwracać wygenerowane ID, wyekstraktowany opis i w przyszłości więcej.
Ewentualnie podział naszego serwisu na dwa moduły - wtedy nasz serwis zwraca tylko true/false - które mówi czy dostaliśmy ogłoszenie czy nie.
Natomiast nowy serwis zajmie się ekstrakcją danych z ogłoszenia.

**Comment by konik32** [comment]
HTML miał być tylko podstawową wersją, żeby coś było. Jeśli uda wam się wyciągnąć opis to super.

**Comment by konik32** [comment]
Postarajcie się pisać swoj moduł  tak aby działał na wielu wątkach(jak najwięcej singletonów, jeśli się nie uda to dla każdego zapytania twórzcie nowy obiekt). Jeśli się nie uda to trudno, ale miejcie to na uwadze.

**Comment by bambalooon** [comment]
Oczywiście tak zrobimy, ja już sobie ustawię beany w springu.
Będzie też to wzór dla ludzi, którzy ze springiem nie mieli do czynienia.

**Comment by ghost** [comment]
Podstawowa wersja PageProcessora z testami jest już gotowa. Ewentualnie jakieś poprawnki jeszcze nanieść w kodzie. Pobiera url z adresem strony. Szuka ogłoszenia. Pobiera ogłoszenie. Wywala z niego znaczniki formatujace i zwraca ogłoszenie jako czysty tekst.

Etap II - zapis plików do bazy danych. Zapisywanie ocen od użytkownika.

Etap III - utworzenie preprocessora, który powycina ze słów polskich końcówki (jak zrobiłam/zrobiłem -> zrobił) i ich zliczenie

Etap IV - nauka komputera rozpoznawania
