### ISSUE TITLE
Podstawowa wersja serwera

### ISSUE THREAD

**Issue by konik32** [maniekstasz/OfferSeeker#16]
1. Zmockowane odpowiedzi dla klienta
2. Rejestracja/logowanie użytkownika
3. Podstawowy model bazy

**Comment by bambalooon** [comment]
Tak w zasadzie - to rejestracja jest konieczna? Nie wystarczy, że serwer wygeneruje UUID i wyśle go klientowi, który zapisze sobie go i już zawsze będzie go używał do komunikacji?
Nie potrzebujemy jakoś specjalnie autoryzacji - nie mamy żadnych 'zaufanych danych',
a szkoda tracić czas na dodatkową robotę - każdy wie, ile razy łatwiej jest napisać serwis bez autoryzacji. No i ja osobiście jak mam jakąś aplikacje/stronę to już mam dość na kolejnej się rejestrować, podawać maila, hasło.. Szkoda czasu użytkownika.
Co o tym myślisz?

**Comment by konik32** [comment]
Klient ma być wieloplatformowy więc UUID odpada. Użytkownik musi mieć co najmniej swój login. Rejestracje zrobiłbym najprostszą: podajesz login serwer sprawdza czy taki istnieje i cie rejestruje albo nie.

**Comment by bambalooon** [comment]
Ok, to pozostańmy przy unikalnym loginie - nic więcej nie jest potrzebne, może to być e-mail.
Uważam też, że powinniśmy mieć w bazie pole timestamp, które będzie nam mówiło, kiedy to ogłoszenie zostało utworzone.
I wtedy w tabeli klienta, będziemy mieli oprócz jego username, będziemy mieli timestamp lub ID ostatniego pobranego ogłoszenia(wtedy timestamp zbędny). W ten sposób klient gdy zostanie uruchomiony, w RQ do serwera poda ID/Timestamp ostatniego otrzymanego ogłoszenia. Żeby serwer mógł mu wysłać tylko nowe ogłoszenia.

**Comment by konik32** [comment]
Zakładając, że pobieramy i zapisujemy wszystkie ogłoszenia to autoryzacja użytkownika nie jest potrzebna. Jeślibyśmy natomiast zapisywali tylko te ogłoszenia które pasują do słów kluczowych podanych przez użytkownika to musielibyśmy ją zrobić.

**Comment by bambalooon** [comment]
Więc nie dodawajmy sobie tej roboty - przynajmniej na razie.
I z naszej rozmowy wynika, że nie takie jest wymaganie projektu.

EDIT:
Spring boot wymaga wersji javy 1.8? Czy to Twoja preferencja @konik32 ?
Bo szczerze, zdecydowanie wolę 1.7, i nie chcę tracić czasu na rozkminianie jakiś lambd i innych pierdół, bo wątpię, żeby było w niej coś co warto by wykorzystać w naszym projekcie.

EDIT:
Serwer startuje, tworzy bazę, ale jeszcze nie jestem w stanie odwiedzić strony localhost:8080, dostaje:

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.
Wed Oct 22 20:59:51 CEST 2014
There was an unexpected error (type=Not Found, status=404).
Not Found

API - nie mieliśmy wyszukiwać po keywordsach, powinniśmy raczej po ID, żeby zwrócić wszystkie nowsze oferty, ew. druga metoda - ID + liczba ofert do pobrania.
Widzę, że zamiast pobierania określonej liczby ofert to używasz tego Pageable, ale nie jestem pewien czy to ma tu sens, chcemy pobrać określoną liczbę ofert, za każdym razem nowych, nie chcemy wracać się do poprzednich.

**Comment by ghost** [comment]
Jeśli dotrwamy do końca to w PageProcessor stworzymy specjalną metodę zliczającą, którą będziemy używać do nauki komputera. Łatwo będzie można ją wykorzystać np. do pobierania jak najtrafniejszych ofert na podstawie słów kluczowych. I wtedy w bazie zapiszemy słowa kluczowe i ewentualnie liczba ogłoszeń dla usera. Ale to ostatni etap. Póki co niech będzie jakaś wersja podstawowa.

**Comment by konik32** [comment]
@bartQH mówił kiedyś, że chciał spróbować javy 1.8 to ją dodałem. Nie znam jeszcze 1.8, więc jak dla mnie również może być 1.7. 

Pageable pobiera z querystringa parametry size(ile zwrócić elementów) oraz page(od którego zacząc), więc to użytkownik decyduje czy chce przeglądać starsze czy nie. 

Co do keywordsów napisałem w #13

**Comment by bambalooon** [comment]
Sory @bartQH - to ja ją usunąłem, bo nie chciało mi się jej instalować... 

@konik32 teraz widzę, że to co mówiłem wczoraj o ID nie jest potrzebne, w ten sposób co proponujesz też może być zaimplementowane.
