### ISSUE TITLE
GumtreePageProcessorTest wywala się

### ISSUE THREAD

**Issue by konik32** [maniekstasz/OfferSeeker#19]
Zerknij na to.

**Comment by ghost** [comment]
![4](https://cloud.githubusercontent.com/assets/7264775/4773660/1df0ff9c-5ba5-11e4-8445-35c00f04296d.png)
tzn?

**Comment by bambalooon** [comment]
@bartQH + za Intellij :D

**Comment by ghost** [comment]
@bambalooon Hehe ale wyłączyłem dark theme tym razem i w sumie pracuje się troszkę lepiej za dnia. ;p

Co z tym błędem?

**Comment by konik32** [comment]
![image](https://cloud.githubusercontent.com/assets/6044569/4774069/70150b0c-5ba9-11e4-9442-06a89d6e0693.png)

**Comment by ghost** [comment]
Zobacz kodowanie. Popatrz jak masz zapisane Male[ństwa, w kodzie jest po polsku, bo nie robiłem żadnych mocków cudów wianków bazy, pliki tylko czysto w kodzie. Pewnie z serwera ściąga się w normalnym kodowaniu i porównuje ze złym. Na gicie też jest kodowanie ok. Sprawdź eclipse. ;p

**Comment by konik32** [comment]
Kodowanie mam utf-8

**Comment by ghost** [comment]
No ale ogarnij ten napis co tam robi ten '[' mam tak:
`private String refDescription = "Maleństwa z ulicy pilnie szukają DT lub DS! PILNE! Na podwórku nie mają szans! <br/>Uratujcie je przed zimą! Maluszki mają około 3 miesiące, mają przed sobą całe życie, potrzebują jedynie pomocy! Kociaki znajdują się w Łomiankach. tel:796096481";`

**Comment by konik32** [comment]
W kodzie jest ok.

**Comment by ghost** [comment]
a mógłbyś wkleić co porównuje i z czym?

**Comment by konik32** [comment]
Jak odpalam Junitem to jest ok. Coś musi być z kodowaniem mavena. Popatrze na to jutro bo zaraz wychodzę

**Comment by ghost** [comment]
No widzisz? Problem solved. ;D

**Comment by konik32** [comment]
Dodałem plugina z kodowaniem. Teraz problem solved :P
