### ISSUE TITLE
PageProcessor etap II 

### ISSUE THREAD

**Issue by konik32** [maniekstasz/OfferSeeker#21]
Moduł powinien:
- zwracać czy zadany link jest ogłoszeniem czy nie niezależnie od portalu
- uczyć się na podstawie ocen od użytkownika
- wstępne wycinanie fragmentów z ogłoszenia typu (tytuł, zawartość) - jeśli wyjdzie

**Comment by ghost** [comment]
Moduł znajduje się w osobnej gałęzi.

Użycie zwykłego pewniaka dla Gumtree:

```
URL url = new URL("http://www.gumtree.pl/cp-inna-odziez-damska/praga-poludnie/zestaw-odziezy-damskiej-xxl-44-46-613718240");
System.out.println("GUM: " + new GumtreePageProcessor().processPage(url).getDescription());
```

Jeśli będzie to inny serwis to zostanie zwrócone ogłoszenie z pustą treścią- a nie **null**.

Rozbudowana wersja:

```
SVMPageProcessor p = new SVMPageProcessor();
        URL url = new URL("http://olx.pl/oferta/odtwarzacz-blu-ray-sony-komplet-CID99-ID7A8NT.html#14f4effa46;promoted");
        Offer offer = p.processPage(url);
        if (offer == null) System.out.println("Nie znaleziono!");
        else {
            System.out.println("SVM: " + offer.getDescription() + " << " + offer.getId());
            p.evaluateOffer(offer.getId(), OfferEvaluation.GOOD);
        }
```

Działa to tak. Po pierwsze napisałem metodę, która z syfnego HTML wyciąga najbardziej znaczące części, które potencjalnie mogą być ogłoszeniami i każde z nich rozmieszcza w osobnej linii. Dodatkowo wszystkie znaczniki formatujące są usuwane oraz wszystkie litery zamieniane na małe.

> na wejści html z hardcorową treścią, a na wyjściu plik z max 10 linijkami zawierającymi np:
> - adres: praga-południe, warszawa, polska
> - copyright
> - zestaw damski rozmiar xxl/ 44-46 na szerokość w biuście 104-110. w zestawie : kurteczka cienka kupiona w tchibo , grubszy jasny , rozpinany sweterek - yessica, ciemna kamizelka z cienkie dzianiny - dłuższa do kolan , rozpiany jasny sweterek ( zebra), brązowa narzutka z rękawem na jeden guzik - akryl , kamizelka polar, 4 sztuki cieniutkich bluzek , 1 cienka bluzko -.narzutka z metką. ubrania są moja własnością, są używane, nie podlegają zwrotowi. mogę przesłać pocztą. cena ok. 20 zł.

I każde w osobnej linii. Są one zapisywane w trzech katalogach - db/orig (trzymane są oryginalne strony), db/offer (trzymane są oferty z nadanymi UUID) oraz db/anti (przeciwstawne oferty - czyli błędne dane w postaci kolejnych numerów). Każdy wpis z osobnej linii jest traktowany jako osobny dokument (!!). Ze strony, w której jest 10 linijek tekstu znaczącego, 1 może być ofertą, a przeciwoferty będzie 9 - więcej syfu będzie usuwać i dobrze. ;)

Przy uruchomieniu programu są zbierane dane i są one podzielone na dwie klasy - offer oraz antioffer (-1.0 oraz 1.0). Są z nich wyciągane cech za pomocą TF-IDF oraz VSM, są następnie zamieniane na problem SVM i wprowadzane do maszyny, która na tej podstawie uczy się rozpoznawania. 

Jeśli SVM znajdzie ogłoszenie to ma on pierwszeństwo i jest zwracana oferta. Jeśli SVM nie poradził sobie ze znalezieniem oferty wtedy szukany jest najdłuższy tekst znaczący, który potencjalnie może być ofertą. Zostaje on zwrócony. Jeśli jest prawdziwy to nic się nie dzieje, bo oferta jest już w bazie. Jeśli natomiast jest zła, wtedy użytkownik zgłasza, że to nie jest oferta - plik przenoszony jest do db/anti i za kolejnym uruchomieniem algorytmu już nie będzie brany pod uwagę - zostanie wzięty kolejny najdłuższy i  kolejny i tak w koło etc. Dzięki temu po którymś razie okaże się, że serwis już zwraca poprawne dane, bo z potencjalne dane mogące być ofertą zazwyczaj są jedyną zmienną linijką tekstu w pobieranych danych znaczących. Jednak to wymaga kilku/kilkunastu błędnych prób.

Do pracy wymagane jest, żeby coś było w bazie, żeby svm mógł za pierwszym razem pobrać jakiś problem. Dlatego też może lecieć wyjątek jak nie macie db / lub macie pustego <- powinno utworzyć się w CWD. ale jak coś to też puściłem commit z bazą.

Mam nadzieję, że tyle wystarczy...

**Comment by ghost** [comment]
Napiszę do tego dokumentacje o co wgl chodzi i ja bym to tak zostawił, bo już nie mam na to siły tak szczerze. Problem nie jest łatwy ale mając więcej czasu można by go było udoskonalić i to znacznie.

I jeszcze jedno - napisałem na szybko programik GUICollector, któremu jak się poda linka to pobiera te cechy, wrzuca w combobox i po wybraniu co jest ogłoszeniem zapisuje to w bazie + antyoferty też zapisuje. Wszystko jednym kliknieciem. ;p
