### ISSUE TITLE
W zwracanych ogłoszeniach znajdują się znaczniki html

### ISSUE THREAD

**Issue by konik32** [maniekstasz/OfferSeeker#24]
Przykładowe ogłoszenia, które zapisują się w bazie:
1. `<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">`
2. `<head>`
3. `<head><meta name='DCSext.loc1' content='gumtree.pl'>`
4. `Serwis opon, wulkanizacja, wymiana opon 50 zł<br/><br/>opony używane FULDA, MICHELIN, KLEBER,<br/>GOODYEAR, DĘBICA, DUNLOP, HANKOOK<br/><br/>Przechowanie OPON sezon komplet tylko 30zł<br/><br/>ul.Piłsudskiego 120<br/>05-091 Ząbki<br/><br/>Godziny pracy: 8.00-20.00<br/>ZAPRASZAMY<br/><br/>Zarezerwuj wizytę już dziś!!!`

**Comment by ghost** [comment]
Wcale nie, zarówno dla jednego jak i do drugiego: ![6](https://cloud.githubusercontent.com/assets/7264775/4991690/028682c2-6997-11e4-9a02-454440453c03.png)

I nie wiem wgl jakim cudem, bo pod uwagę brane są tylko div'y. Napisz dokładnie o co Ci chodzi i w jakiej bazie bo ich jest 3.

wpis w /db/offer/ u mnie - "serwis opon, wulkanizacja, wymiana opon 50 zł opony używane fulda, michelin, kleber, goodyear, dębica, dunlop, hankook przechowanie opon sezon komplet tylko 30zł ul.piłsudskiego 120 05-091 ząbki godziny pracy: 8.00-20.00 zapraszamy zarezerwuj wizytę już dziś!!!"

**Comment by konik32** [comment]
A zmergowałeś branche?

**Comment by ghost** [comment]
Nie, to siedzi na SvmApproach, a nie na master

**Comment by konik32** [comment]
Jeśli działa i jestes zadowolony z efektów to zmerguj.

**Comment by konik32** [comment]
Jest tylko jeden problem. Ta sama oferta przechowywana jest w trzech różnych miejscach. Dasz radę korzystać w algo z bazy serwera?

**Comment by ghost** [comment]
nie, bo potrzebny jest zarowno zbior uczacy negatywny oraz pozytywny i to jest wiele malych pliczkow, ktore na dysku szybko sie przetworza, a w bazie bedzie mega syf, jak chcesz to mozna wywalic przechowywanie oryginalnych stron, bo i tak z tego nikt narazie nie korzysta ;)
