### ISSUE TITLE
Ostatni etap

### ISSUE THREAD

**Issue by konik32** [maniekstasz/OfferSeeker#26]
Do niedzieli chciałbym mieć wszystkie moduły gotowe.
- @bartQH zmerguj jak najszybciej branche
- @jacek22227 zróbcie klienta bo bez tego nie mamy nic. Klient ma wyświetlać oferty, statystyki i alert jeśli pojawiły się nowe oferty z jego keywordsami. 
- zróbcie dokumentacje swoich modułów

**Comment by bambalooon** [comment]
SvmApproach zmergowany do mastera.

**Comment by bambalooon** [comment]
Dodałem instalatory:
https://www.dropbox.com/sh/rx9fwc80gy581tf/AABcVRJ6qEmCHl-v55dVzRyna?dl=0

Testowałem ten na Windowsa, działa ok, raz mi się zdarzyło, że wywaliło Exception, ale odpaliłem drugi raz i już hulało.
Jak macie możliwość to sprawdźcie na linuxie przede wszystkim, na windowsie też się przyda.

**Comment by rampler** [comment]
Dobrze by było gdyby http://localhost:8080/api/offers?keywords="cokolwiek" zwracał jakiekolwiek oferty - na razie content zawsze jest pusty, co trochę utrudnia przetestowanie, czy dobrze parsuje się json po stronie klienta i w ogóle ich wyświetlanie. 

Również uzupełnienie trochę bazy przed pokazaniem mu nie byłoby chyba złym pomysłem, by znów nie robił problemów, że "nic nie widzi" :)

btw.
Zauważyłem, że Crawler po dłuższym czasie informuje o "Shuting down..." i lecą exceptiony - nie wiem czy to zamierzone, czy nie, ale wolę poinformować.

**Comment by konik32** [comment]
Do przetestowania najlepiej jakbys odpalił sobie crawlera żeby pobrał 1000 ofert a potem pageprocessora i bazka się uzupełni. Możesz to zrobic ustawiając crony w application.properties. 

Jakie exceptiony dasz rade je tutaj wkleić?

**Comment by rampler** [comment]
To spróbuje zrobić jak mówisz, choć nie powinno to sie robić automatycznie?
Czy po prostu przed oddaniem sie zmieni crony?

Właśnie zapomniałem skopiować przed restartem serwera - jakby sie jeszcze
pojawiły to wkleję tutaj.
16 lis 2014 00:30 "konik32" notifications@github.com napisał(a):

**Comment by konik32** [comment]
Co masz na mysli przez automatycznie? Algorytmy bd sie uruchamiac o okreslonej w cronie godzinie. Jak bd oddawac to ustawi sie 3.00 dla jednego a 4.00 dla drugiego. Moge zrobic tak zeby algorytm odpalil sie raz przy starcie serwera ale wydaje mi sie to bez sensu. Przy oddawaniu pokazemy mu na swoim kompie gdzie bd juz cos w bazie.

**Comment by konik32** [comment]
Dodatkowo wszelkie properties można ustawiać jako parametry startowe np. `--offerseeker.schedule.pageProccessing.cron="coś tam"`

**Comment by konik32** [comment]
Te exceptiony poprawiłem chodziło o za wczesne zamykanie sesji

**Comment by rampler** [comment]
Jeszcze jedno pytanie - czemu w wszystkich ofertach zwracany url jest null? Nie zostało coś zgubione przypadkiem?

**Comment by konik32** [comment]
Poprawiłem, ale url będzie dodawany do następnych offert
