### ISSUE TITLE
WebCrawler - ciągle szuka w tej samej domenie.

### ISSUE THREAD

**Issue by konik32** [maniekstasz/OfferSeeker#29]
Crawler jest wywoływany w pętli za każdym razem dla innej domeny, a ciągle szuka tylko w pierwszej. Wygląda na to jakby pomiędzy wywołaniami cralwera był zapamiętywany jego stan.

**Comment by gkostalkowicz** [comment]
Wrzuciłem poprawkę, błąd naprawiony. Mam nadzieję że będzie się wszystko buildowało.

Ponieważ wynikało to z błędu w crawler4j najnowszym wydanym (3.5), ściągnąłem najnowszy kod z ich repo i włączyłem go jako źródło do naszego projektu.

Potencjalne problemy jakie trzeba mieć na uwadze to:
1. Zaktualizowana wersja biblioteki, więc zachowanie trochę się zmieniło (ale powinno wszystko działać, weryfikowałem testy jednostkowe)
2. Do PossibleOfferLink dodałem metodę equals() która overriduje tą z AbstractPersistable na potrzeby testów jednostkowych. Mam nadzieję że to niczego nie zepsuje "tam wyżej" :)
