### ISSUE TITLE
Umiejętności

### ISSUE THREAD

**Issue by konik32** [maniekstasz/OfferSeeker#3]
Napiszcie w komentarzach co kto z was lubi pisać (algo, serwer, część wizualną itd), w jakim języku C++/java/perl oraz jakiej technologi używał w tym języku, która mogłaby się przydać do naszego projektu.

**Comment by rampler** [comment]
Ja w sumie mogę się zająć czymkolwiek, ale wolałbym nie bawić się algorytmem. Mogę klienta napisać, który byłby instalowany na komputerze.
Jeżeli chodzi o technologie to:
- Java - Spring, Hibernate, log4j, Grails
- C++ - błagam tylko nie to...
- Bazy - Postgresql to chyba każdy z nas zna i na pewno się przyda

[Edit]
Jak co to C# też może być.

**Comment by jacek22227** [comment]
Jak dla mnie c++, jeśli cokolwiek innego to cześć wizualna, z innymi językami mało miałem do czynienia. Najlepiej jakbym miał bazę do zrobienia ;))

**Comment by ghost** [comment]
Dowolna cześć .NET(fajnie by było coś postawić na tym ale skoro ma to być linux to mono może nam nie wystarczyć), C++ / QT / GTK+, JAVA, PostgreSQL / MSSQL, ReportingServices, MATLAB, PHP, Python. Dowolna technologia webowa i software'owa. Wgl to jeden kij w czym i na czym jak dla mnie. Nawet tego PERLa się nauczę jak nas przyciśnie.

Ogólnie to pewnie najwygodniej dla każdego byłoby:
- JAVA SE 8 - serwer i klient (8 bo chce użyć chociaż raz lambdy w dżawie)
- PHP/HTML/CSS - klient webowy
- PostgreSQL- baza danych

To wszystko było na zajęciach, więc każdy musiał mieć chociaż przez chwile z tym styczność.

No i jeszcze ....
- Assembler - algorytm uczenia się ;D

**Comment by konik32** [comment]
W wymaganiach dot. projektu jest napisane, że mamy użyć c++/java/perl.

**Comment by bambalooon** [comment]
Jeśli nie mamy jakiegoś znakomitego perlowca, to ja bym trzymał się javy, programowanie w c++ zajmuje dużo więcej czasu, no i ja np. już kompletnie nie pamiętam go.
Moim zdaniem nie powinno być problemów w napisaniu części w webowych technologiach, możemy się skonsultować jutro.

Jeśli chodzi o moje skille to:
-JAVA7 - Spring, Hibernate, Maven
-PHP/HTML4/CSS/JS/jQuery - umiem coś, ale szczerze - nie lubię w tym pisać
-postgreSQL
-podstawy Androida

Czym się mogę zająć:
-algorytm
-ogólnie back-end

**Comment by gkostalkowicz** [comment]
Jeśli chodzi o mnie, to też Java, C++ (ale lepiej nie), PostgreSQL. Bez żadnych konkretnych technologii. Troszkę najprostszego HTML/CSS/PHP też.

Bardzo chętnię zajmę się klientem. Ewentualnie coś przy serwerze, ale na pewno nie algo.
