### ISSUE TITLE
Podział pracy

### ISSUE THREAD

**Issue by konik32** [maniekstasz/OfferSeeker#4]
Po tym co widziałem jak piszecie, z opisanych przez was umiejętności oraz tego co chcecie/moglibyście napisać zdecydowałem o takim podziale zadań:

Algorytm:  @bartQH , @bambalooon 
Klient:  @jacek22227, @Munez3
Serwer: @rampler, @konik32
WebSpider: @marcibak, @worldofpiesels   

Jeśli komuś nie pasuje jego przydział to niech zostawi komentarz. @bartQH oraz @jacek22227 będziecie kierownikami swoich grup. Reszta informacji w odpowiednich issues.

**Comment by konik32** [comment]
No trochę tak, ale lepiej żebyś robił coś na czym się znasz. Co do webowych to ustalicie w grupie.

**Comment by Munez3** [comment]
spoko, to pogadam z Bartkiem i ustalimy

**Comment by konik32** [comment]
Przydzieliłem Cie do klienta

**Comment by bambalooon** [comment]
![001](https://cloud.githubusercontent.com/assets/5886748/4706590/0d8e4b68-5886-11e4-81f7-68e13bc9a410.jpg)
Talentu nie mam, ale myślę, że jest zrozumiałe :P
