### ISSUE TITLE
Klient

### ISSUE THREAD

**Issue by konik32** [maniekstasz/OfferSeeker#5]
Przemyślcie w ramach grupy:
- interfejs
- jeden czy dwóch klientów (różny na każdą platformę)
- informacje jakie chcielibyście przechowywać w bazie
- Request/Response z serwerem - jaki byłby najwygodniejszy dla was
- inne rzeczy które przyjdą wam do głowy

Proszę o zapisanie wszystkich tych punktów w komentarzach.

**Comment by gkostalkowicz** [comment]
- interfejs ---> najlepiej Java lub wyrenderować HTML, bo dostaniemy tylko 1 klienta, wszystkie opcje wypisałem w #2. **Musimy jak najszybciej zapytać o to w mailu** - proponuję czekać do środy czy są nowe pytania do prowadzącego, jeśli nie to wysyłać
- jeden czy dwóch klientów (różny na każdą platformę) --->  zależy od powyższego
- informacje jakie chcielibyście przechowywać w bazie ---> tzn. klient nie przechowuje np. ustawień na swoim komputerze, ale na serwerze - dobrze rozumiem?
- Request/Response z serwerem - jaki byłby najwygodniejszy dla was ---> **Format wiadomości** - JSON jest okej, bo w każdym języku łatwo o jego obsługę. **Komunikacja** - Co nam daje REST, bo nie znam się na tym? Przede wszystkim zależy - jeśli klient może być w Javie, to może być REST wg mnie. Jeśli nie, to będziemy w dupie z bibliotekami do obsługi tego REST-a. Także znowu wszystko zależy od tego czy możemy pisać w Javie. Zawsze mogą być też zwykłe sockety. **Powinniśmy** założyć issue o komunikacji klient-serwer i to przedyskutować

**Comment by bambalooon** [comment]
REST działa na standardowych rq HTTP, więc w czymkolwiek mielibyście pisać to wsparcie jakieś będzie.
Co do klienta - jeśli przyjdzie do tego, że zablokują nam Jave i webowe, to bym zrobił na 1 platformę, a jak zdążymy to też na drugą. Będziemy mieli w ten sposób więcej do pokazania, a nie jak ostatnio, wiele rozgrzebanych modułów. 
Jakbyśmy nie zdążyli to powiemy, że to była kolejna faza projektu.

**Comment by gkostalkowicz** [comment]
Jeśli zablokują i Javę, i web, to jeszcze jest opcja np. GTK, Qt, wxWidgets, które działają na obie platformy.

@konik32 Utwórzmy osobny issue to przedyskutujemy tam wspólnie komunikację klient-serwer.
