### ISSUE TITLE
PageProcessor

### ISSUE THREAD

**Issue by konik32** [maniekstasz/OfferSeeker#6]
Przemyślcie w ramach grupy:
- jaka będzie interakcja klienta z algorytmem
- z ilu i jakich modułów będzie sie składał
- interfejs
- jakie informacje i w jakiej formie chcecie przechowywać w bazie
- krótki opis działania algorytmu
- inne

Opiszcie wszystkie punkty w komentarzach.

**Comment by bambalooon** [comment]
I. Interakcja klienta z algorytmem
Moim zdaniem nie powinno być żadnej. Serwer, co np. godzinę odpala algorytm(tyle jeśli chodzi o interakcję z serwerem), algorytm zapisuje oferty do bazy. Klient natomiast czyta jedynie z bazy.

II. Baza
Nie mam jeszcze konkretnego pomysłu, ale proponuje przeglądnięcie przykładowych serwisów, wyłapania części wspólnej, i na tej podstawie próbę stworzenia tabeli.

III. Opis działania algorytmu
Nie mam jeszcze nic konkretnego, ale tak na chłopski rozum, to myślę, że po prostu:
1. Algorytm dostaje linka strony głównej serwisu(np. gumtree.pl). 
2. Wyszukuje wszystkie dostępne linki na stronie, które pozostają na stronie serwisu - gumtree.pl/*.
3. Tworzy sobie drzewo linków odwiedzonych - drzewo nie nawigacji, jak do niego doszliśmy, bo może być wiele sposobów, tylko drzewo w celu szybkiego wyszukiwania, w takim "słowniku".
4. Myślę, że przydałby się jakiś licznik odwiedzin linku. Ten licznik mówiłby ile razy odwiedził robot link i nic znaczącego nie zmieniło się na stronie(znacząca część - trafiająca do bazy). 
Cel tej wartości: jeśli zawartość nie zmieniła się od 10 odwiedzin, to następnym razem jak na nią trafimy to ją pomijamy - omijamy jeden request o stronę i jej analizę. 
Wg mojego myślenia - to końcowe strony z ofertami(konkretna oferta) - nie będą się znacząco zmieniać.
Natomiast strony kategorii, które będą zawierały będą się zmieniały za każdym razem - dodane nowe oferty itd.
5. Strony z ofertami często są podzielone na stronki po x linków - przydałoby się też zauważać, że jeśli strona nie zawiera żadnych nowych linków - wszystkie już odwiedzone to też ją dodać do pomijanych. W ten sposób będziemy w każdej iteracji algorytmu przeglądach tylko przykładowo 10 pierwszych stron kategorii.
6. Oczywiście kolejnym ciężkim i ważnym krokiem jest określenie, że jest to strona z ofertą - tu jest kilka możliwości, albo nauczyć algorytm jak wygląda strona oferty - zaaplikować mu kilkaset stron z ofertą i bez, określając która to która - myślę, że są gotowe algorytmy, które by były w stanie to zrobić - coś pewnie w stylu wyszukiwarki plagiatów. 
7. Ostatecznie zparsowaną ofertę zapisać do bazy, wyciągnąć słowa kluczowe, linki do zdjęć, które prawdopodobnie nie są layoutem - nie powtarzają się na wielu stronach.

**Comment by konik32** [comment]
W punkcie I chodziło o wymaganie dotyczące "Aplikacja powinna raportować znalezione ogłoszenia odpowiadające poszukiwaniu użytkownika – <b>a także na podstawie feedbacku od użytkownika uczyć się oceniać te ogłoszenia<b/>"

**Comment by ghost** [comment]
@bambalooon Nie zgaaaadzam się z jednym. Zajmijmy się algorytmem oceny, a nie algorytmem do wszystkiego. Niech ludzie odpowiedzialni za serwer ogarniają to z logicznego punktu widzenia, niech robią pająka internetowego itd. Naszą częścią niech będzie algorytm, który dostaje treść strony w html i na wyjściu mówi czy jest ogłoszeniem czy nie.I to będzie już bardzo dużo, bo sprawa nie będzie aż taka łatwa.  Mam dużo do czynienia z rozpoznawaniem obrazów ostatnio i tak jak pisałem będzie to działać dość podobnie do tego.

Dzielimy aplikacje na moduły:
- ekstrakcja cech z witryny - będzie wykonywana na każdej stronie dostarczonej przez parametr zarówno dla zbioru uczącego jak i w realnym działaniu - stworzymy interfejs IFeatureExtractor żeby móc zmieniać metody ekstrakcji cech i wybrać najlepszą
- nauka klasyfikatora i zapis wyników do bazy (wykonywane to będzie tylko raz dla ręcznie wybranych ogłoszeń, które sobie wpiszemy na sztywno do jakiegoś pliku czy coś) i wpisanie rezultatu pracy klasyfikatora do bazy - to będzie np. zbiór punktów w przestrzeni klasyfikacji
- odtworzenie nauczonego wcześniej klasyfikatora z bazy w konstruktorze klasy (każdorazowo po uruchomieniu aplikacji) i klasyfikacja

Istnieją różne klasyfikatory - np. SVM.

Czyli tak:
NAUKA - jednorazowo (lub raz na jakiś czas):
- zbieramy strony internetowe z ogłoszeniami i zapisujemy je do naszej własnej bazy ofert do nauki - potrzebne też będą pewnie strony, które nie są ogłoszeniami, żeby istniały dwie różne klasy
- na ich podstawie dokonujemy nauki klasyfikatora (dla każdej strony wyciągamy cechy i to je przetwarzamy)
- to chwile trwa - po zakończeniu wynik zapisujemy w bazie
- sprawdzamy poprawność i wybieramy najlepszą metodę ekstrakcji cech

KLASYFIKACJA - każdorazowo:
- przy uruchomieniu wczytujemy nauczony klasyfikator
- bierzemy strony, wyciągamy cechy
- dostarczamy do klasyfikatora, który to ocenia
- zwracamy wynik true lub false

Tak jak piszesz, żadna interakcja z klientem. Na wejściu będzie nie link ale treść strony internetowej przesłana przez serwer, który odpala algorytm.

Ale zanim cokolwiek zrobimy trzeba przeszukać IEEE Xplore i znaleźć metodę, która daje 90%+ lub nawet 95%+ rozpoznawania treści strony. O ile w przetwarzaniu obrazów czasem to nie jest wykonywalne o tyle tutaj powinno się dać. ;)

Odnośnie tego co napisał @konik32 - mamy folder do nauki (lub może też to być w bazie). Jak user dokona oceny to serwer to wykrywa i uruchamia naszą specjalną metodę - w parametrze dostajemy zawartość strony internetowej oraz czy jest ofertą czy nie) - my to sobie zapisujemy i po ponownym ponownym uruchomieniu nauki klasyfikatora uwzględniamy te wyniki, tak jak pisałem wyżej. Można też zrobić to bez tego o czym pisałem wcześniej czyli ręcznym wyborem bazy początkowej i opierać się tylko na użytkowniku ale baza powinna być odpowiednio duża, więc jak zdamy się tylko na userów to na początku nie będziemy mogli sprawdzić skuteczności algorytmu.

Lepiej byłoby mi to wytłumaczyć ustnie ale starałem się jak mogłem. ;)

**Comment by ghost** [comment]
Post będę edytował w miarę przypływu wiedzy. To jest narazie takie moje głośne myślenie i nie wiem do końca czy to ma sens. Pierwszą wersję algorytmu uogólniłbym tylko do znaczników META czyli tryb **MetaOnly** Dopiero w przyszłości można dodać divy.

**Preprocessing**
Po uzyskaniu strony w postaci HTML należy usunąć z niej nie mające dla nas sensu dane.  Podzieliłbym to na:
- usuwanie znane - przykładowo usuwanie **całych** elementów meta **ALE** z odpowiednimi znanymi i pewnymi properties: np. `keywords`, `robots`, zawierające `google...`, `viewport` lub usuwanie tylko i wyłącznie samych properties jak `action-uri`
- usuwanie blokowe - przykładowo `<!--komentarze -->`,  `<link.../>` `<script>...</script>` czy `<style>...</style>` totalnie nie będzie nam przydatna.
- usuwanie kontekstowe - `!DOCTYPE`, same znaczniki jak `html`, `head`, `body`, formatowanie tekstu `<b>`, pustych linii itd. bez naruszania wnętrza!
- usuwanie liter takich jak `a, i, u, z, od, do`
  Uwaga! Po przejrzeniu kilku stron okazuje się, że dane o ofercie najczęściej siedzą w **head > meta** dlatego **NIE** wolno nam usuwać jak leci całego head'a.

Kolejno należy zamienić wszystkie encje na ich odpowiedniki w tekście: `np. &lt; <`

Następnie zamieniłbym znaki _nawet specjalne_ jak `: _ ; /` i inne z wartości properties na spacje, przykładowo:
`<meta property="og:title" ... />` na `meta property og title`
Dzięki temu lepiej rozpoznamy keywordsy.

Przykład dla wersji **MetaOnly**. Po wczytaniu całej strony zostaje nam:

```
meta property og description content Samochody z USA. Ten i wiele tysięcy innych pojazdów z aukcji samochodowych w USA. Firma RICO Solutions LLC jest oficjalnym przedstawicielem Domów Aukcyjnych 
meta property og title content Toyota Tacoma II
meta property og image ontent http d moto gratka pl auto 6652 ogl 84 18 28350024 A MMM jpg
meta property og url content http moto gratka pl tresc 17530285 html
meta property og site name content Moto.Gratka.pl
meta property og type content website
```

**Feature Extraction**
Zliczanie wystąpień wyrazów w danym dokumencie - to będzie ich waga (coś jak histogram). Następnie zliczamy wszystkie wystąpienia danych wyrazów odpowiednich wyrazów z bazy testowej i obliczamy następną wagę wyrazu:
`waga = ilość_wystąpień_w_aktualnym_doc * log(ilość_dokumentów_w_bazie / ilość_wystąpień_we_wszystkich_dokumentach)`

TODO: coś dopisać więcej

Znalazłem, że coś podobnego znajduje się tutaj, więc może nie będę się już powielał: http://www.ioe.nchu.edu.tw/pic/courseitem/3725_class%2015%20web%20data%20mining%20iii.pdf

W naszym problemie pewnie będziemy musieli najpierw poszukać, która linijka może zawierać opis, która może zawierać autora, która tytuł i która datę utworzenia. Dopiero jak klasyfikator znajdzie wszystkie te rzeczy to wycinamy jest z oryginalnego HTML i zwracamy treść oferty w naszym formacie (lub wpisujemy ją do bazy) i informujemy serwer, że to jest oferta. Jeśli, któreś z nich nie znajdzie to wgl nie bierzemy pod uwagę całej witryny.

**Comment by konik32** [comment]
Po co sobie utrudniać, życie i pisać algorytm decydujący czy coś jest ogłoszeniem czy nie? Piszecie algorytm uniwersalny, który pobiera strony które mogą być ogłoszeniem(np poprzez powtarzalność). Zapisujecie je z odpowiednimi ID kategoryzujecie je. To użytkownik decyduje o tym czy dostał ogłoszenie czy nie i co w tym ogłoszeniu jest tytułem, ceną, wagą, rokiem produkcji. Moim zdaniem tym sposobem robi się to dużo łatwiejsze a i wymaganie dotyczące oceny ogłoszeń na podstawie feedbacku użytkownika jest spełnione. Przykład: pobieramy stronę usuwamy zbędne rzeczy, zostaje nam coś takiego:

`<div class="t">Super BMW</div>`
`<div><p class="description>Kup moje super ultra nieśmigane BMW</p></div>`
`<div><div class="property">1200zł</div></div>`

Parsujemy to na postać:
1. Super BMW | t
2. Kup moje super ultra nieśmigane BMW | description
3. 1200zł | property

Dajemy użytkownikowi do oceny i on stwierdza że 1 to tytuł, 2 to opis, 3 to cena. Zapisujemy to w bazce pod postacią tabela - offers: title, description, tabela properties: offerid, property_name, property_value. Zapisujemy również informację, który obiekt html to była cena, tytuł opis itd i kolejne ogłoszenia już przetwarzamy automatycznie.

Po ocenie użytkownika tego ogłoszenia pobieramy resztę takich ogłoszeń z neta i zapisujemy je już bez interakcji z użytkownikiem. 

Moim zdaniem tak będzie najłatwiej. Zacznijcie od napisania algorytmu pobierającego wszystko co może być ogłoszeniem i okrójcie html do jak najmniejszej postaci. Potem można się zająć uczeniem się.

**Comment by konik32** [comment]
Co do tego, żeby ludzie odpowiedzialni za serwer pisali pająka internetowego to nie uważam to za dobry pomysł. Stwierdziliśmy, że chcemy na początku przygotować podstawową wersję, żeby już coś mieć do pokazania. W związku z tym każdy musi zrobić podstawową wersję swojego modułu. Jeśli powstanie serwer, a z algorytmem będzie za dużo pracy zrobimy przetasowania tak jak podczas budowania wieży.

**Comment by ghost** [comment]
@konik32 Przeglądnij sobie kilka serwisów ogłoszeniowych i zobaczysz, że nigdzie nie ma struktury tak prostej o której pisałeś. Przykładowo dostajesz www.gumtree.pl/cp-produkty-zywnosciowe/praga-poludnie/dzemy-i-soki-okazja-612559880 jak chcesz napisać algorytm usuwający zbędne dane, żeby dla dowolnej strony wychodziło Ci coś podobnego do tego co napisałeś? Dane mogą być w różnych miejscach meta, divy, nawet w js mogą być zaszyte. Jak chcesz wyciągnąć odpowiednie dane i przekazać je użytkownikowi w postaci 'do zjedzenia' automatycznie dla dowolnej witryny nie wpisując nic 'na pałe'?

Co więcej nie uważam (podobnie jak zresztą ze statkami) że taka architektura jest ok. Nie rozumiem dlaczego my mamy ściągać wszystkie dane z podanej strony. Serwer będzie zawierał np. harmonogram cyklicznego odpalania i przeszukiwania oferty. To my też mamy mieć własny osobny harmonogram, który będzie przeglądał na dodatek witryny? Znowu dublujemy kod i zobaczysz, że przy próbie połączenia tego w całość dostaniemy coś ala statki. Co więcej będziemy musieli dopisać do algorytmu moduł, który będzie w stanie łączyć się i pobierać dane z dowolnego serwisu. To wgl dopisując możliwość komunikacji możemy już postawić serwer.

Jak dla mnie - serwer łączy klientów, wymienia z nim dane, sprawdza harmonogram user'a. Jak nastanie odpowiednia pora pobiera stronę dla usera (czy sam, czy przez napisany przez kogoś moduł whatever) i wysyła ją nam.
My - 1) na wejściu strona, na wyjściu oferta lub jej brak 2) na wejściu ewentualna reakcja na rezultat 1) czyli feedback czy jest ok, czy nie lub brak oceny, a my to sobie zapisujemy.

W pierwszej wersji zrobimy to 'na sztywno' np. dla gumtree, żeby coś było. Później rozbudujemy tak, żeby to działało dla dowolnych ogłoszeń.

**Comment by konik32** [comment]
Nie napisałem zbyt jasno o co mi chodziło. Pobieramy stronę z ogłoszeniem znajdujemy jakikolwiek tekst, który ona wyświetla. Identyfikujemy(id, klasa, cokolwiek) elementy, które zawierają tekst i nie ma znaczenia jak bardzo skomplikowana jest struktura strony. Tym identyfikatorom przypisujemy liczby. Wyświetlamy użytkownikowi cały tekst tej strony(oczywiście możemy pominąć headery(nie bawił bym się w znaczniki meta - nie wchodźmy w ten projekt tak głęboko, footery, sidebary, menu, js itd). Jednocześnie, klient(aplikacja) do każdego fragmentu tekstu ma przypisaną określoną w poprzednim kroku liczbę. Pozwalamy użytkownikowi zaznaczyć fragment tekstu i z rozwijanego menu wybrać czy jest to (tytuł, opis, cena, waga, nic nie znacząca informacja itd). Zapisujemy te oceny w bazie. Teraz algorytm, który napotka tego typu ogłoszenie już będzie wiedział co dokładnie ono zawiera. Następny etap to już pobieranie wszystkich tego typu ogłoszeń i zapisaniu ich do bazy już w określonych kolumnach. 

Działanie algo w etapach:
1. Przeszukujemy strony w poszukiwaniu ogłoszen wg algo zaproponowanego przez @bambalooon 
2. Po znalezieniu ogłoszenia sprawdzamy czy tego typu ogłoszenie uzytkownik juz ocenił 
- jeśli nie, pobieramy tylko jedno ogłoszenie, wyciągamy z niego cały tekst i przypisujemy określonym jego fragmentom numery/identyfikatory i łączymy je z identyfikatorami elementów html
- jeśli tak, pobieramy wszystkie z 10 stron. Dla każdego ogłoszenia algo - odszukuje określony element html pobiera jego tekst i zapisuje je w określonym miejscu w bazie zgodnie z oceną użytkownika

Od strony użytkownika:
1. Informujemy użytkownika, że pojawiły się nowego typu ogłoszenia i prosimy o ich ocenę 
2. Użytkownik je ocenia zgodnie z opisem podanym wyżej, zapisujemy te informacje w bazie
3. Za godzinę uzytkownik wraca do apki i ma informację, że pojawiły się nowe już przetworzone ogłoszenia

Algo nie ma harmonogramu. Serwer ma harmonogram i to on odpala algorytm, który przeszukuje zadane strony w poszukiwaniu ogłoszeń. Zapisywanie, odczyt z bazy jest wspólne dla serwera i algo(serwisy, repositoria). Co do łączenia się i pobierania danych z serwisu zerknij na http://jsoup.org/. 

Jestem jutro na SARO, więc możemy podyskutować

**Comment by konik32** [comment]
@bartQH jeśli możesz to przynieś laptopa(mój się na mnie często obraża i się nie oddzywa przez 10-20 min, a potem jest ok) to pokaże o co mi chodzi na podstawie strony, którą podałeś.

**Comment by bambalooon** [comment]
@bartQH jeśli takie są wymagania jak mówisz to ok. Myślałem przez chwile, że trochę inaczej to ma wyglądać. 
Pasuje mi ten układ, że dostajemy tylko stronę, którą mamy ocenić.
Odnośnie tych meta tagów, to wydaje mi się, że proste sprawdzenie, czy słowa z tagów powtarzają się w tekście już nam powie, że dane tam są dość wartościowe - prawda taka, że to jak meta są wypełnione zależy tylko od developera, mogą być opisem głównej strony na każdej podstronie.

Trochę mnie przeraża, że oprócz wyciągnięcia tych danych, będziemy musieli jeszcze dopasować je do każdego użytkownika...

Myślę, że powinniśmy rozpocząć od zbudowania podstawowej wersji każdego modułu, zintegrować je, i następnie nadbudowywać nowymi funkcjonalnościami.
Tak jak ktoś powiedział kiedyś - wybierzmy sobie jedną stronę i zróbmy to trochę statycznie.
W ten sposób szybko zweryfikujemy interfejsy, komunikacje i nasze wspólne zrozumienie.

Na początek jak mówisz, że masz stronę w której większość istotnych informacji jest w meta-tagach, to możemy zrobić system, który wyciąga z meta-tagów tą informację i tyle.

Prawda jest taka, że przy tak dużym integracja może sprawić wiele kłopotu. A jeśli już komunikacja będzie działała między nami, to każdy zespól bezproblemowo będzie mógł rozszerzać swój moduł.
I gdy jeden skończy przed innymi będzie mógł przerzucić swoje zasoby do pozostałych.

Rozpocząłbym pracę wszystkich zespołów od podziału - jedna osoba z zespołu buduje interfejs, konfiguruje środowisko, baze danych i jest w ciągłym kontakcie z odbiorcą/nadawcą, natomiast druga buduje podstawową wersje modułu, opierając się na testach jednostkowych. W junit można bezproblemowo podać do testu plik xml/html/whatever.

EDIT:
Nie odświeżyła mi się strona i nie widziałem, że trochę się rozpisaliście nad tym..
W każdym razie: @konik32 wydaje mi się, że twoja wizja jest mało realna do zrealizowania w miesiąc, nakłada też dodatkowy zbędny nakład na klienta. I takie ocenianie co jest tekstem, a co ceną itd. przez użytkownika.. Jak on miałby to robić? My jakoś dzielimy wg nas stronę, a on wybiera co jest co? To trochę bez sensu - bo już podzieliliśmy jakoś stronę + mogliśmy ją źle podzielić.
Inna opcja: użytkownik dostaje tekst i ma zaznaczyć co jest co..? To już by było ciężkie dla GUI i potem dla nas.
Ja bym nie przejmował się ceną itd. Bo też nie każda oferta ma cenę.. Np. na gumtree są rzeczy "do dogadania się" lub nawet "za darmo". Ja bym się skupił na wyciągnięciu 2 rzeczy: tytuł + opis - czyli cały tekst(również z ceną), który dotyczy oferty. Dodatkowo super by było wyciągnąć zdjęcia z oferty - ale to zostawiłbym na koniec. Dodać do tego link do strony i jest wypas.

Nie jestem pewien czy nie będziemy musieli też stworzyć dodatkowego zespołu do tego pająka - bo to jest jedna z trudniejszych rzeczy(w moim mniemaniu).

@konik32 @bartQH będziecie na projektowych dzisiaj? Zrobiłem fajny schemat, który może nam rozjaśnić problem :)

**Comment by konik32** [comment]
Panowie podstawową rzeczą, którą chciałbym żebyście zrobili jest napisanie algo, które przeglądnie np gumtree i wyciagnie z niego strony, które mogą być ogłoszeniami. Nie ważne w jakim formacie to będzie, może to być nawet html bez żadnych modyfikacji. Mając to zrealizujemy podstawowe wymaganie projektu, potem dodamy reszte.

**Comment by ghost** [comment]
Mam pomysł odnośnie wycinania treści samego ogłoszenia. Na początku na mocku będzie to tylko meta data dla gumtree. 

Później możemy po pierwsze usuwać script i style , po drugie wyciągać tylko zawartość z wartości properties (np. z `<div property="xxxkasklsdfjdklsfjsdf" />`  wyciągniemy xxxkasklsdfjdklsfjsdf) lub zawartość wewnątrz takich elementów, które **nie** mają dzieci (np. `<div>blablabla<div>` da nam blablabla ale już dla elementu wyżej nie dostaniemy nic: `<div><div>blablabla</div></div>`) ale tylko od jakieś określonej długości (trzeba sprawdzić statystycznie mniej więcej od jakiej ilości znaków zaczynają się ogłoszenia).

Tak wyciągnięte dane można grupować liniowo (tzn. usunąć wszystkie nowe linie i zapisywać każdą taką zawartość do osobnej linii). Tylko i tak zapisujmy w bazie oryginalne pliki html, takie jakimi są, bo jak się mylę to żebyśmy mieli pole manewru. Dlatego takie grupowanie należy wykonać przed każdą analizą.

Następnie każdą taką linię z tekstu można potraktować oddzielnie - jako osobny wektor cech (a nie tak jak często proponują - całą stronę jako cechę). Dzięki temu będziemy sprawdzać wszystkie linijki, więc przejdziemy też przez ogłoszenie - i jeśli maszyna stwierdzi, że to chyba ogłoszenie, to będziemy wiedzieć w którym miejscu jest i będziemy mogli pobrać je całe. Cechy możemy pobrać wykorzystując np.  **VectorSpaceMode** z **tf-idf**.

Co więcej - jak użyjemy VSM i tf-idf to tam wykorzystuje się zliczanie słów. Olśniło mnie, że dlatego też np. na serwerze można stworzyć sobie ficzer taki, że serwer pobiera keywords od klienta, następnie bierze i sortuje ogłoszenia po ilości wystąpień wszystkich keywordsów od użytkownika i zwraca mu w takiej własnie kolejności - od najbardziej do najmniej trafnych. Dlatego też można wydzielić później dla serwera właśnie taki moduł, który tego dokonuje na podstawie zbioru ofert.

Date ogłoszenia dopiero pod koniec spróbujemy skitrać z serwera ogłoszeń lub znajdziemy na to jakiś inny patent. Poźniej np. można stworzyć RegEx i szukać daty na takiej stronie. Następnie pobrać wszystkie takie daty i ich rodziców i podobnie wkleić do osobnej linii, następnie zastosować MultiClassSvm i sprawdzać czy rodzic daty jest bardziej datą czy bardziej niczym. Ale to na końcu możemy takie testy zrobić. ;)

**Comment by ghost** [comment]
Może damy do interfejsu 'I'? :D IPageProcessor. @bambalooon  pozmieniaj coś w mojej wizji (jeśli coś nie będzie pasować, nazewnictwo, pomysł, whatever) i commitujemy. ;)

Pytanie - getOffer zwraca Offer lub Null czy jakiś inny pomysł obsługi braku oferty?

```
public interface IPageProcessor {
  Offer getOffer(URL pageLink); 
  void sendFeedback(UUID offerID, Feedback opinion);
}
...
public enum Feedback { Yes, No, NotNow }
...
public class Offer {
 public String description;
 public UUID offerID;
}
```

Generalnie zaznaczam, że w naszej części może się coś zmienić z czasem chociaż tego nie planujemy. ;)

**Comment by bambalooon** [comment]
Co do starszego posta @bartQH to się nie rozpędzaj tak :P - podstawa i wakacje! :D
Co do kodu - już widać styl C# w tym co mówisz :) - Może być.
Weź po prostu to scommituj, nie przejmuj się, jak mi coś nie będzie pasować to poprawie i scommituje. A dzięki temu inni będą mieli jakiś punkt odniesienia.
Dodaj do tego testy jak możesz, jak nie miałeś do czynienia z junitem, to wcommituj co masz, a ja testy dopiszę. Zobaczysz o co chodzi, i będzie z górki. 

Cały czas zastanawiam się czy to powinien być UUID... on jest generowany w runtime, jak nam serw padnie, refresh, cokolwiek, a w bazie pozostaną stare UUID to może być konflikt.
Ale z drugiej strony... szansa na to jest tak mała, a taki błąd można uznać za statystyczny i olać.
Póki nie będziemy mieli logów wypełnionych exceptionami będzie dobrze.

**Comment by ghost** [comment]
Tak jak pisałem w #15 :

Podstawowa wersja PageProcessora z testami jest już gotowa. Ewentualnie jakieś poprawki jeszcze nanieść w kodzie. Pobiera url z adresem strony. Szuka ogłoszenia. Pobiera ogłoszenie. Wywala z niego znaczniki formatujące i zwraca ogłoszenie jako czysty tekst.

Etap II - zapis plików do bazy danych. Zapisywanie ocen od użytkownika. Utworzenie struktury plików. Przemyślenie gdzie to przechowywać.

Etap III - utworzenie preprocessora, który powycina ze słów polskich końcówki (jak zrobiłam/zrobiłem -> zrobił) i ich zliczenie

Etap IV - próba zaimplementowania VectorSpaceMode z tf-idf + nauka komputera rozpoznawania ogłoszeń. Testy.
