### ISSUE TITLE
Serwer

### ISSUE THREAD

**Issue by konik32** [maniekstasz/OfferSeeker#7]
Przemyślcie w ramach grupy:
- Request/Response
- technologie
- informacje jakie musimy przechowywać w bazie
- integracje z pozostałymi modułami
- inne

Opiszcie wszystkie punkty w komentarzach.

**Comment by rampler** [comment]
A więc może tak wstępnie:
- nie wiem czy najlepszym rozwiązaniem nie będzie res/req oparty na socketach i wysyłający zapytania jak i odpowiedzi w postaci JSON. Dobrze byłoby się dowiedzieć, czy komunikacja ma być synchroniczna, czy asynchroniczna, bo jak ta druga to można użyć brokera wiadomości(ZeroMQ ma wsparcie dla wielu języków)
- technologia - na pewno Java - nad resztą można się później zastanowić jak już będzie konkretny zarys jak chcemy połączyć serwer z algorytmem.
- w bazie danych na pewno musimy przechowywać taki dane jak: user(id, login, pass), oferta(id, tytuł, treść, kontakt, link-w celu póżniejszej weryfikacji, czy nie mamy już tego ogłoszenia, datę wygaśnięcia oferty, keywords-opcjonalnie). Nie wiem czy jeszcze coś potrzebujemy na początku.
