### ISSUE TITLE
Motywacja do pracy

### ISSUE THREAD

**Issue by konik32** [maniekstasz/OfferSeeker#8]
Nie mamy zbyt wielu możliwości motywowania do pracy, a chcielibyśmy zrobić projekt jak najmniejszym nakładem pracy co wiąże się z pracą całej grupy. Proponuje system pseudo kar. Oprócz projektu mamy jeszcze zajęcia, po których trzeba przygotowywać raport. Osoby słabo zmotywowane do pracy w danym tygodniu będą miały napisać kolejny raport.

**Comment by konik32** [comment]
Jako, że prawo nie działa wstecz. W tym tygodniu będą tylko upomnienia. @Munez3  oraz Marcin nie wypowiedzieliście się w #3 i #2.

**Comment by gkostalkowicz** [comment]
W ramach zmotywowania wspomnę że projekt musi być gotowy na ok. 20-21 listopada. Mamy miesiąc.
