### ISSUE TITLE
Pytania do projektu

### ISSUE THREAD

**Issue by konik32** [maniekstasz/OfferSeeker#9]
Pojawiły się dziwne wymagania do projektu na zasadzie dowiedzcie się sami czego klient oczekuje. Wpisujcie tutaj wszystkie niejasności związane z projektem zbiorę je i wyśle do prowadzącego.

**Comment by bambalooon** [comment]
Próba przekonania klienta do zrobienia klienta webowego/javowego - tu napisałem o co mi chodzi: https://github.com/stallon2/OfferSeeker/issues/2

**Comment by rampler** [comment]
Komunikacja synchroniczna/asynchroniczna? Wspomniane w: #7

**Comment by konik32** [comment]
Czekam do jutra(21.10.14) na pytania.

**Comment by bambalooon** [comment]
Do godziny?
Nie pytałbym się jego o tą komunikację synch/asynch - myślę, że w naszym przypadku jest to dość naturalne - co gdzie, a nie chcielibyśmy, żeby z dupy coś nam powiedział, a potem będziemy musieli się tego trzymać. Lub bawić się w "przekonywanie klienta do swojej racji".
Nawiasem mówiąc, myślę, że jak potraktujemy w mailu/rozmowie go jak klienta - będziemy go próbowali przekonać do swoich racji logicznymi argumentami(jak w realu), to koleś powinien nas lepiej potraktować. W końcu o to chyba chodzi w tym projekcie - przejść każdą fazę tworzenia oprogramowania.

**Comment by ghost** [comment]
Też się z tym zgadzam @bambalooon. Też wydaje mi się, że tego typu pierdoły nie powinny go (jako klienta) obchodzić. Powinien być zorientowany raczej na rezultat końcowy, a nie sposób jego uzyskania. No ale zobaczymy jak to będzie wyglądać w praktyce. ;D
